FROM nginx:1.13.9-alpine
COPY default.conf /etc/nginx/conf.d/
COPY app/ /var/www/html
RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx \
            && chgrp -R root /var/cache/nginx \
            && sed -i 's/^user/#user/' /etc/nginx/nginx.conf \
            && addgroup nginx root
EXPOSE 8080
USER nginx
