<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Hotel;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Hotel     $hotel
     * @param \DateTime $startYear
     * @param \DateTime $endYear
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     * @return mixed
     */
    public function getAnnualEarnings(Hotel $hotel, \DateTime $startYear, \DateTime $endYear)
    {
        $qb = $this->createQueryBuilder('reservation');
        $qb ->select('SUM(room.price)')
            ->innerJoin('reservation.room', 'room')
            ->where('reservation.hotel = :hotel')
            ->andWhere('reservation.startDate >= :startYear')
            ->andWhere('reservation.startDate <= :endYear ')
            ->setParameter('hotel', $hotel)
            ->setParameter('startYear', $startYear)
            ->setParameter('endYear', $endYear);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
