# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    app.tokens.action_listener:
        class: AppBundle\EventListener\LoggedUserListener
        arguments:
            - '@security.token_storage'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.user.service:
        class: AppBundle\Service\UserService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'
            - '@app.file_uploader.service'
            - '@app.mail_helper.helper'
            - '@app.user.adapter'

        public: true

    AppBundle\Service\UserService: '@app.user.service'

    app.file_uploader.service:
        class: AppBundle\Service\FileUploaderService
        arguments:
            - '%brochures_directory%'

    AppBundle\Service\FileUploaderService: '@app.file_uploader.service'


    app.mail_helper.helper:
        class: AppBundle\Helper\MailHelper
        arguments:
            - '@swiftmailer.mailer'
            - '@twig'
            - '%hotel_email%'

    AppBundle\Helper\MailHelper: '@app.mail_helper.helper'

    AppBundle\Helper\MailInterface: '@AppBundle\Helper\MailHelper'

    app.hotel.service:
        class: AppBundle\Service\HotelService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.hotel.adapter'
        public: true

    AppBundle\Service\HotelService: '@app.hotel.service'

    app.user.adapter:
        class: AppBundle\Adapter\UserAdapter
        arguments:
            - '@app.role.adapter'

    AppBundle\Adapter\UserAdapter: '@app.user.adapter'

    app.room.adapter:
        class: AppBundle\Adapter\RoomAdapter

    AppBundle\Adapter\RoomAdapter: '@app.room.adapter'

    app.hotel.adapter:
        class: AppBundle\Adapter\HotelAdapter

    AppBundle\Adapter\HotelAdapter: '@app.hotel.adapter'

    app.hotel-management.manager:
        class: AppBundle\Manager\HotelManagementManager
        arguments:
            - '@app.hotel.service'
            - '@app.room.service'
        public: true

    app.room.service:
        class: AppBundle\Service\RoomService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.room.adapter'
            - '@app.hotel.adapter'
        public: true

    AppBundle\Service\RoomService: '@app.room.service'

    app.role.adapter:
        class: AppBundle\Adapter\RoleAdapter

    AppBundle\Adapter\RoleAdapter: '@app.room.adapter'

    app.role.service:
        class: AppBundle\Service\RoleService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.role.adapter'
        public: true

    AppBundle\Service\RoleService: '@app.role.service'

    app.reservation.adapter:
        class: AppBundle\Adapter\ReservationAdapter
        arguments:
            - '@app.user.adapter'
            - '@app.hotel.adapter'
            - '@app.room.adapter'

    AppBundle\Adapter\ReservationAdapter: '@app.reservation.adapter'
